---
- name: Update and upgrade packages and reboot servers
  hosts: all
  become: yes
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Reboot the server
      command: reboot
      async: 0
      poll: 0
